### ISSUE TITLE
Reduce the font size of the place holder

### ISSUE THREAD

**Issue by BrianMuhimbura** [tonystar/bootstrap-float-label#11]
i cant seem to reduce the font size of the place holder in the input field

**Comment by tonystar** [comment]
Try to add this code:
```css
.has-float-label .form-control:placeholder-shown:not(:focus) + * {
    font-size: 100%;
    top: 0.6em;
}
```
